Vencord/Vesktop

src/main/mainWindow.ts, src/renderer/components/Settings.tsx, src/shared/settings.d.ts
Changes the main window to use "Vencord" as its title. It's much nicer than having 200 character long window title that changes every-time you navigate
=> Static title

src/main/mainWindow.ts
- Always uses hiding functionality on macOS since the tray doesn't exist and it's the behavior of mainline Discord
- Use `app.hide()` instead of `win.hide()` for built-in activation behavior
=> fix: improve app hiding functionality

src/main/mainWindow.ts
The visible property doesn't seem to work, the menu bar item still is shown on macOS
=> fix: remove duplicate quit items on macOS

src/main/mainWindow.ts, src/renderer/patches/index.ts, src/renderer/patches/platformClass.tsx
<table>
<tr>
<td>Normal Discord</td>
<td>Vencord Desktop</td>
<td>This PR</td>
</tr>
<tr>
<td><img src="https://github.com/Vencord/Desktop/assets/70191398/5bc15f08-9175-4627-a099-98fc3a6e4d9f"></td>
<td><img src="https://github.com/Vencord/Desktop/assets/70191398/00100659-f538-47ec-a4ea-ae53cc88ff55"></td>
<td><img src="https://github.com/Vencord/Desktop/assets/70191398/6b391d35-d73c-4c2a-bb4a-b5b95661583a"></td>
</tr>
</table>
=> feat: use inset title bar style on macOS

src/main/mainWindow.ts
Even tho the tray icon is hilariously big (https://discord.com/channels/1015060230222131221/1026515880080842772/1133902408154624091), this PR removes the tray icon/functionality to stay consistent with the normal Discord client's behaviour.
=> Remove macOS tray icon

src/renderer/components/Settings.tsx
Fix Settings Text to say 'Vesktop' instead of 'Vencord', as per 87595deae749a856dccc115f7a3c32dd759ec537
=> Update Settings Text to Vesktop

package.json
some people don't want to use the nsis-based portable executable to run vesktop, so give them the option of using a zip-based version
=> feat: portable zip

.github/workflows/winget-submission.yml
Based off of Dev Home's Winget CI. `WINGET_PAT` will need to be set with the bot account PAT.
Supersedes and thus closes #98 and closes #100.
=> ci: winget

package.json
It seems the WMClass on Linux still uses the old internal VencordDesktop name, so this PR adds the correct WMClass to the desktop file to resolve it.
Resolves #96.
=> fix: add correct WMClass to desktop file

src/main/ipc.ts
Fixes an issue where AppImage does not relaunch.
> Relevant issue: https://github.com/electron-userland/electron-builder/issues/1727.
> Fix taken from [revoltchat/desktop](https://github.com/revoltchat/desktop/blob/2373e7d6887b57ef8b837d6be53e2fa8b24a6fe0/src/main.ts#L309).
=> fix: appimage not relaunching

pnpm-lock.yaml, src/main/mainWindow.ts, src/main/splash.ts, src/renderer/components/Settings.tsx, src/renderer/index.ts, src/renderer/themedSplash.ts, src/shared/settings.d.ts
Obtains the `--text-normal` and `--background-primary` CSS variables from the CSSOM after document load, saves them in Vencord Desktop settings, and overrides `--fg` and `--bg` in the splash screen with these values if they exist.
=> feat: add splash window theming

package.json
Hello, after installing Vencord Via AppImage, I've noticed that if I use a desktop integration tool, my VM doesn't put them in the same icon (so VMClass)
In the build section of the package.json I've added StartupVMClass as it's what's expected for most desktop environment (I didn't removed VMClass as I don't really know if its useful or not for other things.)
Also it's weird that there are two Icons shipped. like if the app image one has it's own bundled and the app another one. (It doesn't bother at all, but maybe it would be nice to choose what logo is the Icon)
But it's always cleaner to have it in the same VMClass for any desktop.
=> Fix : VM class for AppImage has broken Dekstop integrations

src/main/index.ts, src/renderer/components/Settings.tsx, src/shared/settings.d.ts
Issue https://github.com/Vencord/Vesktop/issues/170
This pull request introduces a new feature in the Vesktop settings, enabling users to disable smooth scrolling throughout the application by integrating the `--disable-smooth-scrolling` flag.
=> feat: Add option to disable smooth scrolling

package.json, pnpm-lock.yaml, scripts/build/build.mts, scripts/build/tsconfig.esbuild.json, src/shared/utils/SettingsStore.ts
- Brings in the latest Electron with its Chromium updates
- Bump to their latest version
- venmic
- aRPC
- all other dev dependencies
- Remove no longer required esbuild workaround (not entirely sure about that but the issue is closed and I haven't faced any issues building or running)
Closes #246
=> Bump dependencies

src/main/ipc.ts, src/main/utils/makeLinksOpenExternally.ts, src/main/utils/steamOS.ts
needs `--filesystem=~/.steam` on the flatpak side
- Refactors SteamOS support to use steam.pipe instead
- Adds support for opening URLs in the steam browser in game mode
- Opens the Vesktop app page in steam instead of attempting to restart Vesktop in game mode (which won't work)
=> SteamOS: add flatpak support using steam.pipe

src/main/mainWindow.ts, src/main/splash.ts
Reimplements #248 to allow starting Vencord minimized/hidden, but with an argument instead of a Settings toggle, so that it may be appended to autostart shortcuts without impacting explicit launching of the app.
Flag is `--start-minimized` to match the official Discord application's flag.
=> feat: Add start minimized as a launch argument

package.json, pnpm-lock.yaml, src/main/venmic.ts, src/preload/VesktopNative.ts, src/renderer/components/ScreenSharePicker.tsx
See Vencord/venmic#15.
This is a draft because [this big boy](https://github.com/Vencord/venmic/actions/runs/7646536541/job/20835545882) is still running
=> Workaround screenshare audio using microphone on debian bug

README.md
Scoop is a command-line installer for Windows, Vesktop is in official Extras repo
=> ADD: Scoop into readme

src/renderer/patches/hideVenmicInput.tsx, src/renderer/patches/index.ts, src/renderer/patches/screenShareFixes.ts
This PR fixes #504 by not patching `navigator.mediaDevices.enumerateDevices` completely but by only patching the function discord uses to retrieve input devices.
=> fix regression breaking venmic

src/main/index.ts
This PR implements the solution in #526.
I am also looking to adding the flags to Vesktop, unfortunately it is impossible to set the argument in time as `app.getGPUInfo()` is async and I don't know if Electron has already initialized the GUI backend by then. It might be worth looking into as a toggle in the settings (probably something like "Experimental Video Decode Acceleration on AMD" but this is so specific it's hard to come out with a suitable name).
=> Allow users to pass --enable/disable-features flag

build/entitlements.mac.plist
With [Vesktop v1.5.1](https://github.com/Vencord/Vesktop/releases/tag/v1.5.1) there was a problem with Vesktop not requesting for permission and rather denying access immediately, I assume it is due to it no longer having an ad-hoc signature, though I don't exactly know the specifics but.... **adding/specifying the entitlements manually** seems to work fine.
Was pretty simple to fix, just adding the entitlements file to `build/` and electron-builder will sign with those entitlements. (not sure why it doesn't use the ones provided in `package.json`..) 
Also, assuming that it required proper entitlements when signed; camera access and access to bluetooth devices most likely didn't exactly work as well.. Though correct me if I'm wrong, I'm not gonna test it as I don't have devices …
=> mac: add entitlements needed for camera/microphone access

README.md
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
=> README: update link to new nixos wiki

src/main/mainWindow.ts, src/shared/settings.d.ts
Resolves #597. Adds a display ID in the state.json file which will then be used to determine if the previously used display is present. If the display is not present, the window will use default x & y values to position itself instead of attempting to position itself out of bounds.
~~Why Windows doesn't check for this I'm not sure~~
=> fix: do not re-position on screen that was disconnected

src/main/mainWindow.ts
Hides the native macOS window controls if the custom discord titlebar is enabled.
Resolves #631 
Old behavior:
New behavior:
=> mac: hide native window controls with custom titlebar enabled

src/renderer/patches/enableNotificationsByDefault.ts, src/renderer/patches/hideSwitchDevice.tsx
Noticed and fixed those:
```
Patch by Vesktop had no effect (Module id is 292959): /\.isPlatformEmbedded(?=\?[A-Za-z_$][\w$]*\.DesktopNotificationTypes\.ALL)/g
Patch by Vesktop had no effect (Module id is 897607): /([A-Za-z_$][\w$]*)\.default\.getState\(\).neverShowModal/
```
=> Update some broken patches

meta/dev.vencord.Vesktop.metainfo.xml
Messaging applications should use the Network category, not AudioVideo.
See: https://specifications.freedesktop.org/menu-spec/latest/apa.html
---
I noticed this when I saw Vesktop on Flathub in the AudioVideo category where it looks quite out of place.
=> meta: Use Network category instead of AudioVideo

src/renderer/components/ScreenSharePicker.tsx, src/renderer/patches/screenShareFixes.ts
change minimum framerate to match chosen value in order to stop unnecessary frame drops on wayland (demo video attached)
especially relevant when streaming videos from a web browser
i've seen at least one other person mentioning what i believe to be this bug in the support channel on discord
this may also fix frame drops i've experienced on X11 when streaming games but i haven't tested 
discord is @puppyears if u need to ask me a question i honestly don't use github and am unfamiliar with this api, i just noticed a problem that bothered me so i tried to fix it
probably relevant information:
nvidia-dkms 555.58-1
kde plasma 6.1.1-1
https://github.com/Vencord/Vesktop/assets/95729061/3b1876b3-ffef-413c-9d08-8915802a3283
=> fix: specify framerate in constraints

package.json
On RHEL based systems a fix must be made to Electron apps to not include debugging symbols (see similar issue for vscode repository [here](https://github.com/microsoft/vscode/pull/116105/)).
This PR adds the fix to the package.json in order to build rpms without those debugging symbols and be able to install multiple electron apps without issues.
=> fix(rpm): don't generate build_id links to avoid conflicts

src/renderer/components/ScreenSharePicker.tsx
Vanilla client supports sharing screen in 4k.
Patch gui preview:
Due to other issues with screenshare main purpose for it is screensharing text (e.g. code), because it is still low quality comparing to original windows discord client 😔
=> Add 4k resolution to screenshare

README.md
I thought it's not bad people to add extra info, I recently came around this and it made wayland screensharing less pain in the neck,
Thank you guys for developing this!
=> README.md: add slackware link to unofficial repos

src/main/arrpc.ts, src/renderer/arrpc.ts, src/renderer/index.ts, src/renderer/patches/index.ts, src/renderer/patches/nativeFocus.tsx, src/shared/IpcEvents.ts
This implements deep links from web so message links and the like work over just invites working.
Depends on OpenAsar/arrpc/pull/128
I noticed we didn't implement this after double checking what I said in a #813 comment
note: you need to be signed out of web for discord to prompt you for this
=> feat(rpc): implement arrpc's `link` event

package.json, patches/arrpc@3.5.0.patch, pnpm-lock.yaml, src/renderer/arrpc.ts, src/renderer/patches/index.ts, src/renderer/patches/streamerMode.ts
resolves: #790 
note: as usual with arrpc process scanning— this will not work in the flatpak. see https://github.com/flatpak/flatpak/issues/3922
=> arrpc: support OBS auto streamer mode

.github/ISSUE_TEMPLATE/bug_report.yml
Update the debug-logs textarea to use the render feature, which automatically makes the content of the textarea into a code block, instead of requiring the default value with backticks.
=> Enhance debug-logs textarea on bug report ISSUE_TEMPLATE

src/main/index.ts, src/main/mainWindow.ts
Matches stock client behavior. If people want this back, they should add a keybind to their WM instead, which makes it configurable.
Fixes #934
=> fix: don't close app on Ctrl+W
