src/main/mainWindow.ts

debatable whether they are needed, I think they would be useful

Tray: Add more buttons

---

src/main/mainWindow.ts
src/renderer/components/Settings.tsx
src/shared/settings.d.ts

Another trivial change!
Having a tray icon can often feel cluttered ;p
if the user doesn't switch off minimise to tray now... uhh... I'm wondering what the best solution for this is :P

Tray: Option to hide

---

src/main/mainWindow.ts

Matching with https://github.com/Vendicated/Vencord/pull/849

feat: implement translucency for macOS

---

package.json

Add MacOs arm64 build

---

src/main/firstLaunch.ts
src/main/index.ts
src/main/mainWindow.ts
src/shared/settings.d.ts
static/first-launch.html

Implements https://github.com/Vencord/Desktop/issues/22

Add first launch tour

---

package.json

Fixes package installation on node 20: https://github.com/pnpm/pnpm/issues/6424

Update pnpm in package.json

---

src/main/ipc.ts
src/main/screenShare.ts
src/main/utils/vencordLoader.ts

merge this along with Vendicated/Vencord#1477

vecord: download proper vesktop specific preload & renderer css

---

package.json
pnpm-lock.yaml

Fixes #125 for me
Version 25.8.2 has the security fix as well

Downgrade electron to v25.8.2

---

.github/workflows/winget-submission.yml

Works on Linux which should in theory be faster than a Windows runner, + it uses Komac which ironically has much better support for Winget manifest generation than Microsoft's own tooling.

ci: switch to vedantmgoyal2009/winget-releaser

---

package.json
pnpm-lock.yaml

https://github.com/NixOS/nixpkgs/issues/258048

Bump Electron to 25.8.4 for CVE-2023-5217

---

.gitignore
src/main/mainWindow.ts

macos users dont break every other platform challenge

fix turnary soup in main window options

---

package.json
pnpm-lock.yaml
src/main/virtmic.ts
src/preload/VesktopNative.ts
src/renderer/components/ScreenSharePicker.tsx

Updates venmic to v2.0.0.
(As soon as [this workflow](https://github.com/Vencord/venmic/actions/runs/6826944806/job/18567971401) is finished I'll also update to v2.0.1 to resolve #217)

feat: update venmic

---

src/main/utils/steamOS.ts

Fixes the left trackpad scrolling mode (it was on circular, changed it to vertical so it works properly)

Update steamdeck controller layout

---

static/views/splash.html

unblur shiggy in splash screen

---

src/main/utils/steamOS.ts

[see discussion in discord](https://discord.com/channels/1015060230222131221/1015063227299811479/1187770248632487986)

fix(security): use promise queue for steam pipe

---

src/main/mainWindow.ts
src/main/splash.ts
src/renderer/components/Settings.tsx
src/shared/settings.d.ts

This reverts commit 40b952d8bf75d437b2e6425c2a116ddead66c3f7.

Revert "feat: Add start as minimized toggle to settings (#248)"

---

src/main/mainWindow.ts

See https://github.com/electron/electron/issues/29937#issuecomment-1193030133

Remove `transparent: true` for transparencyOption

---

src/renderer/components/ScreenSharePicker.tsx

This PR stops venmic when the stream is ended instead of channel disconnect/switch

Stop venmic on stream stop

---

package.json
pnpm-lock.yaml

Bump venmic to `3.3.3`

---

package.json
pnpm-lock.yaml
src/main/venmic.ts
src/preload/VesktopNative.ts
src/renderer/components/ScreenSharePicker.tsx
src/renderer/components/screenSharePicker.css

- Add support for changing default speakers mid screen-share
- Improve Logging
- Several logic improvements (+ rohrkabel updates)

Venmic v3.4

---

package.json
pnpm-lock.yaml
src/main/venmic.ts
src/preload/VesktopNative.ts
src/renderer/components/ScreenSharePicker.tsx
src/renderer/patches/hideSwitchDevice.tsx
src/renderer/patches/index.ts
src/renderer/patches/screenShareAudio.ts

Improve Venmic Usability

---

.github/workflows/winget-submission.yml
package.json
pnpm-lock.yaml
src/main/venmic.ts
src/preload/VesktopNative.ts
src/renderer/components/ScreenSharePicker.tsx
src/renderer/components/screenSharePicker.css
src/shared/settings.d.ts

---
---
> [!NOTE]
> The settings in the screenshot do not represent the defaults :)
Fixes #619
Fixes #218

linux audioshare: add granular selection, more options, better ui

---

src/renderer/components/ScreenSharePicker.tsx

Change default screen-sharing quality to 720p 30 FPS

---

src/renderer/components/screenSharePicker.css

this pr fixes screenshare picker alignment issues, also adds consistency
| CURRENT  | THIS PR |
| ------------- | ------------- |
| <img width="378" alt="image" src="https://github.com/user-attachments/assets/563850f0-2056-4628-ba98-6ca1aee9db9c">| <img width="457" alt="image" src="https://github.com/user-attachments/assets/55ebd0c4-e2ef-44ff-8ac1-a5929877dad0"> |

fix screenshare picker window subtitle alignment

---

static/views/splash.html

Insane issue that I finally bothered to look at
fixes: #858

correctly set splash background

---

src/main/firstLaunch.ts

fix: First start ui being blank on windows

---

src/main/screenShare.ts

Causes computer audio to be muted when screensharing with audio

Revert loopbackWithMute to loopback
